# Path-sanitized primary run configuration.
model: cudalstm
dataset: japan
package_version: 1.12.0
seed: 595126
device: cuda:0
epochs: 20
batch_size: 64
seq_length: 365
predict_last_n: 1
hidden_size: 64
head: regression
loss: MSE
optimizer: Adam
output_activation: linear
output_dropout: 0.4
initial_forget_bias: 3
clip_gradient_norm: 1
target_noise_std: 0.005
learning_rate:
  0: 0.001
  10: 0.0005
  20: 0.0001
dynamic_inputs:
  - hist_pr
  - hist_tas
  - ssr
  - sd
  - snowc
  - sf
  - swvl1
  - swvl_deep
  - stl1
  - wind_speed
  - PET
static_attributes:
  - precip_mean
  - temp_mean
  - snowfall_mean
  - snow_fraction
  - snow_depth_mean
  - elev_mean
  - slope_mean
  - landuse_shannon
target_variables:
  - QObs
train_start_date: 01/01/1993
train_end_date: 31/12/1999
validation_start_date: 01/01/2000
validation_end_date: 31/12/2001
test_start_date: 01/01/2002
test_end_date: 31/12/2003
data_dir: DATA_DIR_TO_BE_PROVIDED_BY_USER
train_basin_file: BASIN_FILE_TO_BE_PROVIDED_BY_USER
validation_basin_file: BASIN_FILE_TO_BE_PROVIDED_BY_USER
test_basin_file: BASIN_FILE_TO_BE_PROVIDED_BY_USER

